# Moodle Plugin CI configuration for local_aynurasurveys.
# See https://moodlehq.github.io/moodle-plugin-ci/

# PHP Mess Detector ruleset.
phpmd: phpmd.xml

# Paths and filenames to ignore in code checks.
filter:
  notNames:
    - "*.min.js"
  notPaths:
    - templates/
